---
title: "Assignment 1"
author: "Jennifer Horowitz"
date: "9/7/2020"
output: html_document
---
```{r load libraries}
library(tidycensus)
library(tidyverse)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warnings = FALSE, message = FALSE)
```
```{r}
hh_vars_2018 <- pums_variables %>%
  distinct(year, survey, var_code, 
           var_label, data_type, level) %>%
  filter(level == "housing", year == 2018, survey == "acs1")
```



```{r}
person_vars_2018 <- pums_variables %>%
     distinct(year, survey, var_code, 
              var_label, data_type, level) %>%
     filter(level == "person", year == 2018, survey == "acs1")
```
```{r}
hh_vars_2018 <- pums_variables %>%
  distinct(year, survey, var_code, 
           var_label, data_type, level) %>%
  filter(level == "housing", year == 2018, survey == "acs1")
```

```{r}
area_vars_2018 <- load_variables(2018, "acs1")
```

```{r}
area_vars_2010 <- load_variables(2010, "sf1")
```

```{r}
person_data <- get_pums(variables = c("TEN", 
                                      "SEX", 
                                      "PINCP", 
                                      "WKHP", 
                                      "JWMNP"),
                        state = "TX", 
                        year = 2018, 
                        survey = "acs1",
                        recode = TRUE) %>%
  filter(JWMNP > 0) %>%
  select(TEN_label, SEX_label, PINCP, WKHP, JWMNP)
```

```{r}
person_data
```

```{r}
hh_data <- get_pums(variables = c("TEN", 
                                  "YBL", 
                                  "BDSP", 
                                  "GRNTP", 
                                  "BLD",
                                  "LNGI"),
                        state = "CA", 
                        year = 2018, 
                        survey = "acs1",
                        recode = TRUE) %>%
  filter(TEN_label == "Rented") %>%
  mutate(age_struct = case_when(
    YBL_label == "1939 or earlier" ~ 100,
    YBL_label == "1940 to 1949" ~ 73,
    YBL_label == "1950 to 1959" ~ 63,
    YBL_label == "1960 to 1969" ~ 53,
    YBL_label == "1970 to 1979" ~ 43,
    YBL_label == "1980 to 1989" ~ 33,
    YBL_label == "1990 to 1999" ~ 23,
    YBL_label == "2000 to 2004" ~ 16,
    YBL_label == "2005" ~ 13,
    YBL_label == "2006" ~ 12,
    YBL_label == "2007" ~ 11,
    YBL_label == "2008" ~ 10,
    YBL_label == "2009" ~ 9,
    YBL_label == "2010" ~ 8,
    YBL_label == "2011" ~ 7,
    YBL_label == "2012" ~ 6,
    YBL_label == "2013" ~ 5,
    YBL_label == "2014" ~ 4,
    YBL_label == "2015" ~ 3,
    YBL_label == "2016" ~ 2,
    YBL_label == "2017" ~ 1,
    YBL_label == "2018" ~ 0)) %>%
  select(age_struct, BDSP, GRNTP, BLD_label, LNGI_label)
```
```{r}
hh_data
```

```{r}
pop_vars <- c(workers_16 = "B23025_002",
          unemp_pop_16 = "B23025_005",
          college_25 = "B23006_023",
          popln_25 = "B23006_001",
          med_income = "B06011_001",
          tot_pop = "B01003_001",
          white_pop = "B01001A_001")

rural_vars <- c(total_hh = "H002001",
                rural_hh = "H002005")

counties2018 <- get_acs(geography = "county", 
                        variables = pop_vars, 
                        output = "wide",
                        year  = 2018,
                        survey = "acs1")

counties_rural <- get_decennial(geography = "county", 
                                variables = rural_vars, 
                                output = "wide",
                                year = 2010)

counties <- inner_join(counties2018, counties_rural, by = "GEOID") %>%
  mutate(pct_college = college_25E / popln_25E,
         unemp_rate = unemp_pop_16E / workers_16E,
         majority_white = white_popE / tot_popE > 0.5,
         rural = rural_hh == total_hh) %>%
  select(pct_college, unemp_rate, med_incomeE, 
                majority_white, rural)

counties
```
## saving data

You can save any of the datasets you just created for future use by writing them to a "csv file. 
